name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
    - run: git config --global user.name "Na Jongwoo"
    - run: git config --global user.email "njw1204@naver.com"
    - run: yarn install --frozen-lockfile
    - run: yarn deploy
